### ISSUE TITLE
Doesn't work in IE11 `Object doesn't support property or method 'includes'`

### ISSUE THREAD

**Issue by denieler** [vimeo/player.js#323]
### Actual Behavior

There is the error in console for IE 11:

`Doesn't work in IE11 `Object doesn't support property or method 'includes'`
player.js (2,249087)

### Steps to Reproduce
Just run video in IE11, reproducing even on api/demo page of Vimeo.

**Comment by ricardodrummond** [comment]
I need that fix too.

**Comment by fisherinnovation** [comment]
This should be corrected now. Thanks for reporting. Please reopen if you are still noticing this issue.

**Comment by denieler** [comment]
@fisherinnovation was it a release in the last few hours? Or how it should be fixed?

**Comment by ricardodrummond** [comment]
It looks like it's working.

**Comment by fisherinnovation** [comment]
@denieler It was a player update not an API update. No change is required on your end.

**Comment by rajeevmehrotra** [comment]
Looks like this issue is back.  `player.js` has the `includes` method again.  

The CDN is giving me Vimeo Player v3.5.3
[link](https://f.vimeocdn.com/p/3.5.3/js/player.js)

**Comment by idMolotov** [comment]
@denieler 

can you check that you have all required for the IE11 shims and polyfill's added to the imports/load

```
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'babel-polyfill';
....
```
