### ISSUE TITLE
loadVideo providing vimeo url in options object doesn't work

### ISSUE THREAD

**Issue by pchiwan** [vimeo/player.js#372]
### Expected Behavior

I should be able to load a video on a player's instance by calling `loadVideo` passing in an options object with the vimeo url.

### Actual Behavior

Player's `loadVideo` doesn't work if you provide an options object with the url property as parameter, it only works with the vimeo id.

### Steps to Reproduce

Here's a code example:
https://jsbin.com/sumajacefo/edit?html,console,output

When loading the page I instantiate the player using an options object with the `url`. If I then try to load a different video using `loadVideo` with an options object as well, it doesn't work. According to the repo's [README](https://github.com/vimeo/player.js#loadvideooptions-numberobject-promisenumberobject-typeerrorpassworderrorerror) `loadVideo` should accept both an options object or a number, but I can only get it to work with the vimeo id.

**Parsing the vimeo url in order to obtain the id is not an option for me, because I need to load unlisted and/or private vimeos.**

Any workarounds? Thanks!

**Comment by fisherinnovation** [comment]
Thanks for reporting this! We will work to resolve this issue ASAP. In the mean time the optimal work around we ensure we properly support the `url` is to just pass the video ID as a `id` param in the `loadVideo` call.

```
document.getElementById("reload").addEventListener('click', () => {
      player.loadVideo({
        id: 96457131
      })
        .then(console.log)
        .catch(console.error)
    })
```

**Comment by pchiwan** [comment]
Hey @fisherinnovation, thanks for your quick response! 

Yes using `loadVideo` with the `id` is a valid workaround but only if I'm not loading private videos, and that's why I can't use it. In the meantime the workaround that I'm using is to `destroy` and re-instantiate the player.

Thanks!

**Comment by davekiss** [comment]
Running into this same issue when trying to use `unlisted` (private link format ie. https://vimeo.com/vimeo_video_id/12345abcde)

**Comment by luwes** [comment]
This issue should be resolved. Just a few notes:
If this format currently works for you

```js
new Vimeo.Player(id, {
	url: 'https://player.vimeo.com/video/293438045/463ebf7bcf'
})
```

then this should work too

```js
player.loadVideo('https://player.vimeo.com/video/293438045/463ebf7bcf?autoplay=1')
```

or 

```js
player.loadVideo({
	url: 'https://player.vimeo.com/video/293438045/463ebf7bcf',
	autoplay: 1
});
```

Testable here https://player.vimeo.com/api/demo
By pasting the url (https://player.vimeo.com/video/293438045/463ebf7bcf) in load video field and pressing the button.


I'm little bit puzzled though, I believe the private hash can be left off.
Could you try and let me know? I'll do some more testing as well.

**Comment by davekiss** [comment]
@luwes thanks for the update – I'm not sure why, but I'm seeing an error for that particular Vimeo video when I attempt to load it into the player

`NotFoundError: Because of its privacy settings, this video cannot be played here.`

The video that I have which is marked as only viewable with the private link seems to be working as expected now when I load by either url or by ID, though, contrary to the notes in the README, the private hash is not required to load it in.

**Comment by luwes** [comment]
sorry about that @davekiss, I didn't add the domain player.vimeo.com to the whitelist of that video yet. not it works again.

I'm closing this issue as it's resolved. It's possible now to load the next video with 

```js
player.loadVideo('https://player.vimeo.com/video/293438045?autoplay=1')
```

or 

```js
player.loadVideo({
	url: 'https://player.vimeo.com/video/293438045',
	autoplay: 1
});
```

The unlisted hash is indeed not required for the loadVideo call.

At the moment it is required in the Vimeo.Player constructor because we retrieve the embed code via our oEmbed api. If you prefer not to publish your private link with the unlisted hash in your source code, it's recommended to embed the Vimeo player directly with an iframe instead. This will just work granted the referrer matches the whitelisted domain.

**Comment by pchiwan** [comment]
Thanks! 👏

**Comment by jakubkrolikowski** [comment]
I think the bug is back or similar.
My video is private, this is the link:

`https://vimeo.com/616885681/79bcd7654f`

Can be embedded "anywhere".

This:

`player.loadVideo('https://player.vimeo.com/video/616885681?autoplay=1')`

or:

`loadVideo('https://vimeo.com/616885681/79bcd7654f?autoplay=1')`

or 

`loadVideo('https://vimeo.com/616885681?autoplay=1')`

creates request:

`https://player.vimeo.com/video/616885681/config?h=1b82718d37&title=0&byline=0&portrait=0&autoplay=1&app_id=122963&referrer=https%3A%2F%2Fwww.piecsmakow.pl%2F`

with the response 404 and body:

`{"message": "This video does not exist.", "title": "Sorry", "view": 7}`

**Comment by eduardoliron** [comment]
As @jakubkrolikowski pointed out, the problem seems to be due to wrong parsing of the url as it generates an extra `/config` as the parsed result.

by now, I have manually corrected the `https://vimeo.com/` url with this simple script.

```
const urlParts = url.split('/');
correctUrl = `https://player.vimeo.com/video/${urlParts[urlParts.length - 2]}?h=${urlParts[urlParts.length - 1]}`
```

The solution for this issue doesn't seem to be that complex to still not implemented.
