### ISSUE TITLE
 controls=0 not being respected on embedded player

### ISSUE THREAD

**Issue by frausto** [vimeo/player.js#866]
### Expected Behavior
Controls should not be seen if `controls=0` is set in the embedded player.

### Actual Behavior
Controls have started showing up even though `controls=0` is set. This is a new behavior as of today.

### Steps to Reproduce
Click the image below.

[<img width="465" alt="image" src="https://user-images.githubusercontent.com/352853/199299937-bcab9020-855a-488f-bc27-c81832ee4e4d.png">](https://www.adaptedmind.com/Math-Worksheets.html)

**Comment by joeldavuk** [comment]
This might be something changed at vimeo end as we are also seeing this issue, if you open your embeded video url in the browser directly it is showing the same behaviour with background=1 controls=0

**Comment by ellafitz** [comment]
I am using background=1 to get rid of the "tap to unmute" sign on mobile devices. It was ok a few hours ago, but reappeared when I just checked. Hope it can be resolved. Website has just been launched.

**Comment by nroca** [comment]
Just chiming in to say seeing the same on all my landing pages (8+) that use vimeo to play background videos. Play/Pause shows on load then on hover, as well as the picture in picture button. All videos are using the `?background=1` parameter.

**Comment by Marcdj-02** [comment]
+1; having the same problem. Without any changes to the code, we've got the play button, our logo and an empty stoke of control bar showing. Using the `?background=1&controls=0`

**Comment by emidaniele** [comment]
+1. Having the same problem. `background=1` is not working on mobile (paid account). The `tap to unmute` button is shown now.

**Comment by rkrishnan8594** [comment]
This issue should now be fixed. Please file a new issue if you're still observing incorrect behavior when applying these parameters.

**Comment by ellafitz** [comment]
The Tap to unmute on mobile is still there

**Comment by liamcrean** [comment]
This is not fixed.

**Comment by luke-hale** [comment]
can also confirm, this is not fixed yet: 
![IMG_C36730BF3EA2-1](https://user-images.githubusercontent.com/60442292/199454986-69cd04bd-cf40-4765-9a8d-e6b63d1e6863.jpeg)

**Comment by dikodahan** [comment]
Still not fixed on my side as well!
